using UnityEngine;
using Unity.AI.Navigation;

public class ProceduralMapManager : MonoBehaviour
{
    [Header("Validation")]
    public NavMeshSurface navMeshSurface;
    public MapValidator mapValidator;
    public int maxGenerationRetry = 10;

    [Header("Data")]
    public ChapterThemeData chapterTheme;
    public MapGenerationSettings settings;

    [Header("Seed")]
    public bool useSavedSeed = true;
    public int seed = 123456;

    [Header("Input")]
    public KeyCode regenerateKey = KeyCode.Slash;

    [Header("Roots")]
    public Transform mapRoot;
    public Transform runtimeRoot;
    public Transform debugRoot;

    [Header("Generators")]
    public RoadNetworkGenerator roadNetworkGenerator;
    public BuildingPlacer buildingPlacer;
    public POIPlacer poiPlacer;
    public EnvironmentObjectPlacer environmentObjectPlacer;
    public ThrowObjectPlacer throwObjectPlacer;
    public SpawnPointGenerator spawnPointGenerator;

    [Header("Runtime")]
    public PlayerSpawnManager playerSpawnManager;

    private MapContext currentContext;

    private void Start()
    {
        LoadOrCreateSeed();
        Generate();
    }

    private void Update()
    {
        if (Input.GetKeyDown(regenerateKey))
        {
            GenerateNewRandomSeedAndMap();
        }
    }

    private void LoadOrCreateSeed()
    {
        if (useSavedSeed && SeedStorage.HasSavedSeed())
        {
            seed = SeedStorage.LoadSeed();
            Debug.Log($"Loaded saved seed: {seed}");
            return;
        }

        seed = CreateRandomSeed();
        SeedStorage.SaveSeed(seed);

        Debug.Log($"Created new seed: {seed}");
    }

    private void GenerateNewRandomSeedAndMap()
    {
        seed = CreateRandomSeed();
        SeedStorage.SaveSeed(seed);

        Debug.Log($"New random seed generated by key input: {seed}");

        Generate();
    }

    private int CreateRandomSeed()
    {
        return Random.Range(1, int.MaxValue);
    }

    /*
    [ContextMenu("Generate Map")]
    public void Generate()
    {
        ClearChildren(mapRoot);
        ClearChildren(runtimeRoot);
        ClearChildren(debugRoot);

        currentContext = new MapContext
        {
            seed = seed,
            random = new System.Random(seed),
            theme = chapterTheme,
            settings = settings,
            mapRoot = mapRoot,
            runtimeRoot = runtimeRoot,
            debugRoot = debugRoot,
            navMeshSurface = navMeshSurface
        };

        if (!ValidateReferences())
            return;

        roadNetworkGenerator.Generate(currentContext);
        buildingPlacer.Place(currentContext);
        poiPlacer.Place(currentContext);
        environmentObjectPlacer.Place(currentContext);
        throwObjectPlacer.Place(currentContext);
        spawnPointGenerator.GenerateEnemySpawns(currentContext);

        if (playerSpawnManager != null)
            playerSpawnManager.SpawnPlayer(currentContext.startPosition);

        Debug.Log($"Map generated. Chapter={chapterTheme.chapterName}, Seed={seed}");
    }
    */

    [ContextMenu("Generate Map")]
    public void Generate()
    {
        for (int attempt = 0; attempt < maxGenerationRetry; attempt++)
        {
            ClearChildren(mapRoot);
            ClearChildren(runtimeRoot);
            ClearChildren(debugRoot);

            int attemptSeed = seed + attempt;

            currentContext = new MapContext
            {
                seed = attemptSeed,
                random = new System.Random(attemptSeed),
                theme = chapterTheme,
                settings = settings,
                mapRoot = mapRoot,
                runtimeRoot = runtimeRoot,
                debugRoot = debugRoot,
                navMeshSurface = navMeshSurface
            };

            if (!ValidateReferences())
                return;

            roadNetworkGenerator.Generate(currentContext);
            buildingPlacer.Place(currentContext);
            poiPlacer.Place(currentContext);
            environmentObjectPlacer.Place(currentContext);
            throwObjectPlacer.Place(currentContext);
            spawnPointGenerator.GenerateEnemySpawns(currentContext);

            bool valid = true;

            if (mapValidator != null)
                valid = mapValidator.Validate(currentContext);

            if (!valid)
            {
                Debug.LogWarning($"Map validation failed. Retry {attempt + 1}/{maxGenerationRetry}");
                continue;
            }

            if (playerSpawnManager != null)
                playerSpawnManager.SpawnPlayer(currentContext.startPosition);

            Debug.Log($"Map generated. Chapter={chapterTheme.chapterName}, Seed={attemptSeed}");

            return;
        }

        Debug.LogError("Map generation failed after max retry.");
    }

    private bool ValidateReferences()
    {
        if (chapterTheme == null)
        {
            Debug.LogError("ChapterTheme is missing.");
            return false;
        }

        if (settings == null)
        {
            Debug.LogError("MapGenerationSettings is missing.");
            return false;
        }

        if (mapRoot == null || runtimeRoot == null)
        {
            Debug.LogError("Root transforms are missing.");
            return false;
        }

        if (roadNetworkGenerator == null)
        {
            Debug.LogError("RoadNetworkGenerator is missing.");
            return false;
        }

        if (buildingPlacer == null)
        {
            Debug.LogError("BuildingPlacer is missing.");
            return false;
        }

        if (poiPlacer == null)
        {
            Debug.LogError("POIPlacer is missing.");
            return false;
        }

        if (environmentObjectPlacer == null)
        {
            Debug.LogError("EnvironmentObjectPlacer is missing.");
            return false;
        }

        if (throwObjectPlacer == null)
        {
            Debug.LogError("ThrowObjectPlacer is missing.");
            return false;
        }

        if (spawnPointGenerator == null)
        {
            Debug.LogError("SpawnPointGenerator is missing.");
            return false;
        }

        if (navMeshSurface == null)
        {
            Debug.LogError("NavMeshSurface is missing.");
            return false;
        }

        if (mapValidator == null)
        {
            Debug.LogError("MapValidator is missing.");
            return false;
        }

        return true;
    }

    private void ClearChildren(Transform root)
    {
        if (root == null) return;

        for (int i = root.childCount - 1; i >= 0; i--)
        {
#if UNITY_EDITOR
            if (!Application.isPlaying)
                DestroyImmediate(root.GetChild(i).gameObject);
            else
                Destroy(root.GetChild(i).gameObject);
#else
            Destroy(root.GetChild(i).gameObject);
#endif
        }
    }
}